# Generated by Django 5.2.1 on 2025-06-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('rate_limit_per_window', models.IntegerField(default=1000, help_text='Max requests allowed within the rate limit window.')),
                ('rate_limit_window_seconds', models.IntegerField(default=3600, help_text='Duration of the rate limit window in seconds (e.g., 3600 for 1 hour).')),
            ],
        ),
    ]
