# Generated by Django 5.2.1 on 2025-06-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_key_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(blank=True, db_index=True, max_length=64, unique=True),
        ),
    ]
